typography_spectrum: 0.811477982904762
color:
  brandStrength: 0.18098401837050915
  lightness: 0.09862087736837566
  saturation: 0.12428443785756826
  rhythmicContrast: 0.8466932589653879
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.8678233735263348
author:
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9a49d15e-6aea-42b5-87f1-ae0ed2d5fb15.jpg
name: Integrate Tax
navigation:
  - id: 64f602c5-1d2c-42d7-b0a2-385077813c7a
    url: 2016-07-21-our-team.html
    name: About Us
    type: content
  - id: 81acee7b-d44a-4d44-b662-88dc35c37c37
    url: 2016-07-21-state.html
    name: Services
    type: content
  - id: 020ca7b9-e7d6-4af8-838f-0367428e9f8a
    url: 2016-07-21-tax-questions.html
    name: Support 24/7
    type: content
  - id: 647297b3-a5d4-4118-b7ad-b68b71587e70
    url: 2016-07-21-jumpstart-your-tax-return.html
    name: Jumpstart Tax Return
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e91a948a-4383-42a4-a8f1-2f840c5ce507.png
title: Taxation with Innovation
